VERSION 0.8
IMPORT ../../base/alpine
IMPORT ../../base/ubuntu
IMPORT ../../installer
IMPORT ../../haskell

test-build:
  FROM alpine+alpine3.19.1
  DO installer+SETUP_HASKELL --GHC=9.6.4 --HPACK_VERSION=0.36.0
  WORKDIR /test
  DO haskell+INIT
  COPY --keep-ts . . # COPY cannot understand some globs(e.g. "**").
  DO haskell+FREEZE_WITH_STACKAGE --LTS_VERSION=lts-22.9
  DO haskell+CABAL --args="update"
  DO haskell+BUILD --extra_args="--jobs=4"

test-test:
  FROM alpine+alpine3.19.1
  DO installer+SETUP_HASKELL --GHC=9.6.4 --HPACK_VERSION=0.36.0
  WORKDIR /test
  DO haskell+INIT
  COPY --keep-ts . . # COPY cannot understand some globs(e.g. "**").
  DO haskell+FREEZE_WITH_STACKAGE --LTS_VERSION=lts-22.9
  DO haskell+CABAL --args="update"
  DO haskell+TEST --extra_args="--jobs=4"

test-production:
  FROM ubuntu+ubuntu20.04
  DO installer+SETUP_HASKELL --GHC=9.6.4 --HPACK_VERSION=0.36.0
  WORKDIR /test
  DO haskell+INIT
  COPY --keep-ts . . # COPY cannot understand some globs(e.g. "**").
  DO haskell+FREEZE_WITH_STACKAGE --LTS_VERSION=lts-22.9
  DO haskell+CABAL --args="update"
  DO haskell+PRODUCTION_BUILD --target="all" --extra_args="--jobs=4 --constraint=\"vector -boundschecks\""

test-production-build-llvm:
  FROM ubuntu+ubuntu20.04-llvm12
  DO installer+SETUP_HASKELL --GHC=9.6.4 --HPACK_VERSION=0.36.0
  WORKDIR /test
  DO haskell+INIT
  COPY --keep-ts . . # COPY cannot understand some globs(e.g. "**").
  DO haskell+FREEZE_WITH_STACKAGE --LTS_VERSION=lts-22.9
  DO haskell+CABAL --args="update"
  DO haskell+PRODUCTION_BUILD_LLVM --target="all" --extra_args="--jobs=4 --constraint=\"vector -boundschecks\""

test-production-build-static:
  FROM alpine+alpine3.19.1
  DO installer+SETUP_HASKELL --GHC=9.6.4 --HPACK_VERSION=0.36.0
  WORKDIR /test
  DO haskell+INIT
  COPY --keep-ts . . # COPY cannot understand some globs(e.g. "**").
  DO haskell+FREEZE_WITH_STACKAGE --LTS_VERSION=lts-22.9
  DO haskell+CABAL --args="update"
  DO haskell+PRODUCTION_BUILD_STATIC --target="all" --extra_args="--jobs=4 --constraint=\"vector -boundschecks\""
  RUN file output/production-static/* | grep 'statically linked'

test-bench:
  FROM alpine+alpine3.19.1
  DO installer+SETUP_HASKELL --GHC=9.6.4 --HPACK_VERSION=0.36.0
  WORKDIR /test
  DO haskell+INIT
  COPY --keep-ts . . # COPY cannot understand some globs(e.g. "**").
  DO haskell+FREEZE_WITH_STACKAGE --LTS_VERSION=lts-22.9
  DO haskell+CABAL --args="update"
  DO haskell+BENCH --extra_args="--jobs=4"

test-all:
  BUILD +test-build
  BUILD +test-test
  # BUILD +test-bench
  BUILD +test-production
  BUILD +test-production-build-llvm
  BUILD +test-production-build-static
