VERSION 0.8

IMPORT ../../base/alpine
IMPORT ../../base/ubuntu
IMPORT ../../installer
IMPORT ../../haskell

TEST_CABAL:
  FUNCTION
  ARG --required GHC
  DO installer+SETUP_HASKELL --GHC=$GHC
  WORKDIR /example
  RUN cabal init --non-interactive --is-executable example
  WORKDIR /example/example
  RUN cabal v2-build example
  RUN echo test | $(cabal list-bin example) | grep 'Hello, Haskell!'

TEST_CABAL_STATIC:
  FUNCTION
  ARG --required GHC
  DO installer+SETUP_HASKELL --GHC=$GHC
  WORKDIR /example
  RUN cabal init --non-interactive --is-executable example
  WORKDIR /example/example
  RUN cabal v2-build example --enable-tests --enable-benchmarks --only-dependencies
  RUN cabal v2-build example --enable-executable-static
  RUN file $(cabal list-bin example) | grep 'statically linked'
  RUN echo test | $(cabal list-bin example) | grep 'Hello, Haskell!'

test-cabal-ubuntu:
  FROM ubuntu+ubuntu20.04
  DO +TEST_CABAL --GHC=9.6.4

test-cabal-static:
  FROM alpine+alpine3.19.1
  DO +TEST_CABAL_STATIC --GHC=9.6.4

test-build:
  FROM alpine+alpine3.19.1
  DO installer+SETUP_HASKELL --GHC=9.6.4 --HPACK_VERSION=0.36.0
  WORKDIR /test
  DO haskell+INIT
  COPY --keep-ts . . # COPY cannot understand some globs(e.g. "**").
  DO haskell+FREEZE_WITH_STACKAGE --LTS_VERSION=lts-22.9
  DO haskell+CABAL --args="update"
  DO haskell+BUILD --extra_args="--jobs=4"

test-test:
  FROM alpine+alpine3.19.1
  DO installer+SETUP_HASKELL --GHC=9.6.4 --HPACK_VERSION=0.36.0
  WORKDIR /test
  DO haskell+INIT
  COPY --keep-ts . . # COPY cannot understand some globs(e.g. "**").
  DO haskell+FREEZE_WITH_STACKAGE --LTS_VERSION=lts-22.9
  DO haskell+CABAL --args="update"
  DO haskell+TEST --extra_args="--jobs=4"

test-production:
  FROM ubuntu+ubuntu20.04
  DO installer+SETUP_HASKELL --GHC=9.6.4 --HPACK_VERSION=0.36.0
  WORKDIR /test
  DO haskell+INIT
  COPY --keep-ts . . # COPY cannot understand some globs(e.g. "**").
  DO haskell+FREEZE_WITH_STACKAGE --LTS_VERSION=lts-22.9
  DO haskell+CABAL --args="update"
  DO haskell+PRODUCTION_BUILD --target="all" --extra_args="--jobs=4 --constraint=\"vector -boundschecks\""

test-production-build-llvm:
  FROM ubuntu+ubuntu20.04-llvm12
  DO installer+SETUP_HASKELL --GHC=9.6.4 --HPACK_VERSION=0.36.0
  WORKDIR /test
  DO haskell+INIT
  COPY --keep-ts . . # COPY cannot understand some globs(e.g. "**").
  DO haskell+FREEZE_WITH_STACKAGE --LTS_VERSION=lts-22.9
  DO haskell+CABAL --args="update"
  DO haskell+PRODUCTION_BUILD_LLVM --target="all" --extra_args="--jobs=4 --constraint=\"vector -boundschecks\""

test-production-build-static:
  FROM alpine+alpine3.19.1
  DO installer+SETUP_HASKELL --GHC=9.6.4 --HPACK_VERSION=0.36.0
  WORKDIR /test
  DO haskell+INIT
  COPY --keep-ts . . # COPY cannot understand some globs(e.g. "**").
  DO haskell+FREEZE_WITH_STACKAGE --LTS_VERSION=lts-22.9
  DO haskell+CABAL --args="update"
  DO haskell+PRODUCTION_BUILD_STATIC --target="all" --extra_args="--jobs=4 --constraint=\"vector -boundschecks\""
  RUN file output/production-static/* | grep 'statically linked'

test-bench:
  FROM alpine+alpine3.19.1
  DO installer+SETUP_HASKELL --GHC=9.6.4 --HPACK_VERSION=0.36.0
  WORKDIR /test
  DO haskell+INIT
  COPY --keep-ts . . # COPY cannot understand some globs(e.g. "**").
  DO haskell+FREEZE_WITH_STACKAGE --LTS_VERSION=lts-22.9
  DO haskell+CABAL --args="update"
  DO haskell+BENCH --extra_args="--jobs=4"

test-all:
  BUILD +test-cabal-ubuntu
  BUILD +test-cabal-static
  BUILD +test-build
  BUILD +test-test
  # BUILD +test-bench
  BUILD +test-production
  BUILD +test-production-build-llvm
  BUILD +test-production-build-static
